### PR TITLE
Changed `declare module "electron"` to export = Electron

### LINKED ISSUE #33: Simplify AllElectron
Instead of

```
interface AllElectron {
  app: Electron.App;
  autoUpdater: Electron.AutoUpdater;
  BrowserWindow: typeof Electron.BrowserWindow;
  BrowserWindowProxy: typeof Electron.BrowserWindowProxy;
  ClientRequest: typeof Electron.ClientRequest;
  clipboard: Electron.Clipboard;
  contentTracing: Electron.ContentTracing;
  Cookies: typeof Electron.Cookies;
  crashReporter: Electron.CrashReporter;
  Debugger: typeof Electron.Debugger;
  desktopCapturer: Electron.DesktopCapturer;
  dialog: Electron.Dialog;
  DownloadItem: typeof Electron.DownloadItem;
  globalShortcut: Electron.GlobalShortcut;
  IncomingMessage: typeof Electron.IncomingMessage;
  ipcMain: Electron.IpcMain;
  ipcRenderer: Electron.IpcRenderer;
  Menu: typeof Electron.Menu;
  MenuItem: typeof Electron.MenuItem;
  nativeImage: typeof Electron.NativeImage;
  net: Electron.Net;
  powerMonitor: Electron.PowerMonitor;
  powerSaveBlocker: Electron.PowerSaveBlocker;
  protocol: Electron.Protocol;
  remote: Electron.Remote;
  screen: Electron.Screen;
  session: typeof Electron.Session;
  shell: Electron.Shell;
  systemPreferences: Electron.SystemPreferences;
  TouchBar: typeof Electron.TouchBar;
  Tray: typeof Electron.Tray;
  webContents: typeof Electron.WebContents;
  webFrame: Electron.WebFrame;
  WebRequest: typeof Electron.WebRequest;
  webviewTag: Electron.WebviewTag;
}
```

it can be generated as

```
interface AllElectron extends MainInterface, RendererInterface {
}
```

### LINKED ISSUE #55: Import both type and it's constructor under the same name
I want to be able to write code like that
```ts
import {BrowserWindow} from "electron";
let win: BrowserWindow;
win = new BrowserWindow();
```
But it gives me `error TS2304: Cannot find name 'BrowserWindow'.` on type of `win`

This code
```ts
import * as e from "electron";
let win: Electron.BrowserWindow;
win = new Electron.BrowserWindow();
```
compiles to 
```js
let win;
win = new Electron.BrowserWindow();
```
which is invalid since it's relying on global `Electron` and not on imported one. And from source it's unclear where did `Electron` even come from.

My suggestion: replace namespace with module and proper class exports in type definitions. Like this
```ts
declare module 'electron' {
  export class BrowserWindow { /*...*/ }
}
```
With this first example will compile fine to
```js
const electron_1 = require("electron");
let win;
win = new electron_1.BrowserWindow();
```

### PR DESCRIPTION
**Pull request by NaridaL**
and added const declarations so that `app` etc are accessible.

Fully backwards compatible. I also added a couple of lines to the main.ts to test the changes.

Fixes #55

Also fixes #33 because it was bugging me.

### CODE REVIEW

**Comment by NaridaL** [comment]
@darsain

File: base/base_footer.ts [hunk 1]
```diff
@@ -1,10 +1,9 @@
 declare module 'electron' {
-  const electron: Electron.AllElectron;
-  export = electron;
+  export = Electron;
```
Comment (MarshallOfSound) [inline base/base_footer.ts]: I'm concerned this isn't 100% backward compatible, the interface exposed by `AllElectron` is not the same as `Electron`.  I'll run this locally and see if it builds with my TS projects.

/cc @bpasero being the biggest TS project I know, could you validate the typings outputted by this change as well.  Would hate to break you guys 👍

File: index.js [hunk 2]
```diff
@@ -18,6 +18,7 @@ const wrapWithHeaderAndFooter = (outputLines, electronVersion) => {
   const newOutputLines = []
   utils.extendArray(newOutputLines, fs.readFileSync(path.resolve(__dirname, 'base/base_header.ts'), 'utf8').replace('<<VERSION>>', electronVersion).split(/\r?\n/))
 
+  newOutputLines.push('/** @deprecated */')
```
Comment (MarshallOfSound) [inline index.js]: Don't think we want to deprecate this, we can quite easily have both 👍

File: base/base_footer.ts (hunk 1 above)
Comment (NaridaL) [reply base/base_footer.ts]: Yes, I modified the Electron namespace. https://github.com/electron/electron-typescript-definitions/pull/78/files#diff-aedc36ee7cf303f0616c4eaa52999c85R74

File: index.js (hunk 2 above)
Comment (NaridaL) [reply index.js]: If the module itself doesn't declare a global variable, neither should the typings.

File: base/base_footer.ts (hunk 1 above)
Comment (bpasero) [reply base/base_footer.ts]: @MarshallOfSound happy to try it out if there is a electron.d.ts to play with.

Comment (NaridaL) [reply base/base_footer.ts]: @bpasero https://gist.github.com/NaridaL/fedfa9e4272683be12d172eea0a28dee

Comment (bpasero) [reply base/base_footer.ts]: Does not seem to produce any new errors. Is the idea to no longer use Electron.* to declare types?

Comment (NaridaL) [reply base/base_footer.ts]: @bpasero Exactly, you should be able to do 
```
import {BrowserWindow} from 'electron'
const myBW: BrowserWindow = new BrowserWindow()
```

File: index.js (hunk 2 above)
Comment (MarshallOfSound) [reply index.js]: @NaridaL Technically electron does make magic globals, for instance `process.windowsStore` and other such things.  I'm happy to add this new way of doing things in if that's what people want but not keen on "deprecating" the old way 👍

File: tslint.json [hunk 3]
```diff
@@ -13,6 +13,7 @@
     "no-namespace": false,
     "quotemark": false,
     "unified-signatures": false,
-    "variable-name": false
+    "variable-name": false,
+    "no-shadowed-variable": false
```
Comment (MarshallOfSound) [inline tslint.json]: I actually strongly agree with this rule (and the rule above), shadowing variables is pretty bad, can we just use another variable name instead of disabling the rule 😄

**Comment by MarshallOfSound** [comment]
Just a thing about the linting then this looks GTG

File: tslint.json (hunk 3 above)
Comment (NaridaL) [reply tslint.json]: It doesn't make much sense in a declarations file.
```ts
namespace Electron {
  declare const webContents: ...;
  class BrowserWindow {
    static fromWebContents(webContents: WebContents): BrowserWindow;
  }
}
```
The error in on `webContents`, which seems like a non-issue, and as it's generated from the .json, changing it is non-trivial.

Comment (MarshallOfSound) [reply tslint.json]: @NaridaL Lel, thought this was linting our code / tests not the output 👍

**Comment by zeke** [comment]
Thanks for doing this, @NaridaL.

Are we good to go here? If so I'll merge and cut a new release.

This seems like a breaking change. Should we wait until the next major of Electron to use this?

**Comment by darsain** [comment]
> Should we wait until the next major of Electron to use this?

If you decide to go this route, please provide a way how to consume this definition types now so we don't have to wait a year for next electron major. It's quite cumbersome to use current definition types :(

**Comment by NaridaL** [comment]
@zeke, this change doesn't break anything, a minor version should be fine.

On Sep 24, 2017 10:07 AM, "darsain" <notifications@github.com> wrote:

Should we wait until the next major of Electron to use this?

If you decide to go this route, please provide a way how to consume this
definition types now so we don't have to wait a year for next electron
major. It's quite cumbersome to use current definition types :(

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/electron/electron-typescript-definitions/pull/78#issuecomment-331694456>,
or mute the thread

**Comment by NaridaL** [comment]
@zeke, @MarshallOfSound anything which remains to be cleared up so this can be merged?

**Comment by zeke** [comment]
Thanks, @NaridaL. This change will land in the next release of Electron, regardless of whether that ends up being a major, minor, or patch bump.

```
~/git/electron/electron-typescript-definitions master
$ np patch
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies using npm
 ✔ Running tests
 ✔ Bumping version using npm
 ✔ Publishing package
 ✔ Pushing tags

 electron-typescript-definitions 1.2.9 published 🎉
```
