### PR TITLE
Change default optional value for methods and events

### LINKED ISSUE #48: All event listener parameters are incorrectly optional
For example:

```ts
on(event: 'login', listener: (event?: Event,
                              webContents?: WebContents,
                              request?: Request,
                              authInfo?: AuthInfo,
                              callback?: (username?: string, password?: string) => void) => void): this;
```

This causes a lot of `error TS2532: Object is possibly 'undefined'.` errors in our codebase.

Compare this with the [@types/electron](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cf735753cf6ad4b75c30c45558a8a44daccb19f6/types/electron/index.d.ts#L170-L174) definitions:

```ts
on(event: 'login', listener: (event: Event,
  webContents: WebContents,
  request: LoginRequest,
  authInfo: LoginAuthInfo,
  callback: (username: string, password: string) => void
) => void): this;
```

cc @zeke @MarshallOfSound

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #48 

/cc @felixrieseberg You made the original change before to default this to true for everything, it appears to was purely to fix all the constructor object properties needing to be optional by default so I think this still covers that case

### CODE REVIEW

File: cli.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ if (inFile) {
 
 const typeCheck = () => {
   const tscExec = path.resolve(require.resolve('typescript'), '../../bin/tsc')
-  const tscChild = childProcess.spawn(tscExec, ['--project', 'tsconfig.json'], {
+  const tscChild = childProcess.spawn('node', [tscExec, '--project', 'tsconfig.json'], {
```
Comment (MarshallOfSound) [inline cli.js]: Just so it works on windows 😆

**Comment by zeke** [comment]
```
❯ np patch
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies using Yarn
 ✔ Running tests
 ✔ Bumping version using Yarn
 ✔ Publishing package
 ✔ Pushing tags

 electron-typescript-definitions 1.2.4 published 🎉
```
